### ISSUE TITLE
Reading SRG will add the mapped name of fields as field types

### ISSUE THREAD

**Issue by noeppi-noeppi** [MinecraftForge/SrgUtils#12]
Reading a SRG file, the mapped class and field name will be added as descriptor. It seems like there something got messed up in the [loadSRG](https://github.com/MinecraftForge/SrgUtils/blob/master/src/main/java/net/minecraftforge/srgutils/InternalUtils.java#L79-L108) method. While XSRG includes field descriptors, SRG doesn't, so `descriptor` should not be called [here](https://github.com/MinecraftForge/SrgUtils/blob/master/src/main/java/net/minecraftforge/srgutils/InternalUtils.java#L95).

Simple test code: (Using [this](https://gist.github.com/noeppi-noeppi/f58d9b6f7f6813c5c95c29376d63edf7) example SRG file)
```java
IMappingFile mf = IMappingFile.load(Files.newInputStream(Paths.get("joined.srg")));
IMappingFile.IField field = mf.getClasses().stream().flatMap(cls -> cls.getFields().stream()).findFirst().get();
System.out.println(field.getOriginal() + " -> " + field.getMapped());
System.out.println(field.getDescriptor() + " -> " + field.getMappedDescriptor());
```
which prints
```
someField -> someMappedField
pkg/Mapped/someMappedField -> pkg/Mapped/someMappedField
```

As you can see, the mapped class and field names appear as descriptor in the `IMappingFile`. Writing the mappings as `tsrg2` with
```java
mf.write(Paths.get("joined.tsrg"), IMappingFile.Format.TSRG2, false);
```
gives a tsrg2 file with invalid field descriptors:
```
tsrg2 left right
pkg/Original pkg/Mapped
	someField pkg/Mapped/someMappedField someMappedField
```

**Comment by forgedev-teamcity** [comment]
You are indeed correct, seems like a little copy pasta issue from a long long time ago. i'll fix that up real quick.

**Comment by LexManos** [comment]
You are indeed correct, seems like a little copy pasta issue from a long long time ago. i'll fix that up real quick.
