### ISSUE TITLE
Broken TSRG2 writer

### ISSUE THREAD

**Issue by Elec332** [MinecraftForge/SrgUtils#19]
With this library one should theoretically be able to "remap" any mapping type to another, e.g. TINY to TSRG2.

after trying this out with a full TINY map (containing official, intermediary and named mappings) I found the TSRG2 writer to not function as intended. 

The following code: 
```
        def mappings = INamedMappingFile.load(Path.of("mappings/mappings.tiny"))
        mappings.write(Path.of("output.tsrg"), IMappingFile.Format.TSRG2, "named", "intermediary")
```
Should produce a named -> intermediate mapping. It instead produced a official to intermediate mapping. Other types worked as intended, so I tried the following code:
```
        def mappings = INamedMappingFile.load(Path.of("mappings/mappings.tiny"))
        mappings.getMap("named", "intermediary").write(Path.of((output.tsrg"), IMappingFile.Format.TSRG2, false)
```
which worked as expected.

This led me to believe the TSRG2 writer didnt respect the order input
I found that every type (class, field, method ect) uses the following code to write mappings:

```
private String getTsrg2(int... order) {
            StringBuilder ret = new StringBuilder();
            for (int x = 0; x < order.length; x++) {
                ret.append(getName(x)).append('/');
                if (x != order.length - 1)
                    ret.append(' ');
            }
            return ret.toString();
 }
```

This code does indeed not respect the order, or even the contents, it just considers the length and rolls with it.
A simple fix could be to change `ret.append(getName(x)).append('/');` to `ret.append(getName(order[x])).append('/');`

(Same issue as https://github.com/neoforged/SRGUtils/issues/3)

**Comment by LexManos** [comment]
Ya, Small oversight. Simple enough fix.
