### ISSUE TITLE
ProGuard reader crashes when encountering descriptors which contain root-level classes

### ISSUE THREAD

**Issue by NebelNidas** [MinecraftForge/SrgUtils#20]
Classes without package lead to a crash, since non-primitive types are only recognized if they contain a `/`:
https://github.com/MinecraftForge/SrgUtils/blob/917096ea6a3a8087c564d90a86c8ec236f9a96c6/src/main/java/net/minecraftforge/srgutils/InternalUtils.java#L568-L569

**Comment by LexManos** [comment]
You need to provide real world functional examples when filing reports.

**Comment by NebelNidas** [comment]
```
class1 -> class1Rename:
    class2 field1 -> field1Rename
```
should do

**Comment by NebelNidas** [comment]
Thanks! :)
